---
name: Métodos y estado
locale: es
type: learning
beta: false
teacher_info: ''
language: wollok
id_format: "%05d"
order:
- 22
- 18
- 3
- 23
- 4
- 5
- 8
- 25
- 24
- 20
- 21
- 7
- 9
- 26
private: false
